name: CI/CD

# workflow triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: run test
      run: npm run test
    - name: Build step
      run: npm run build
      env:
        VITE_APP_PUBLIC_URL: /example-react-cicd  # --> /example-react-cicd/
      name: uploading build files
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      jobs:
      job1:
    
      job2:
      needs: job1
      jobs:
  deploy:
    permissions:
      contents: write
      steps:
- name: Uploading build files
  uses: actions/upload-artifact@v2
  with:
    name: artifact
    path: <artifact_path>
    steps:
- name: Downloading artifact
  uses: actions/download-artifact@v2
  with:
    name: artifact
    path: <artifact_path>
      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: <artifact_path>




    # TODO: Complete the steps in CICD.md
